sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
  - make -C build
before_deploy:
  - git tag "draft-$(date +'%Y%m%d')-$(git log --format=%h -1)"
deploy:
  provider: releases
  edge: true
  api_key: $github_access_token
  file_glob: true
  file: build/*.pdf
  cleanup: true
  on:
    repo: riscv/riscv-isa-manual
    branch: master
