name: Build RISC-V PRIV and UNPRIV PDFs and HTMLs Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - riscv-isa-asciidoc
  pull_request:
    branches:
      - main
      - riscv-isa-asciidoc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Pull the latest RISC-V Docs container image
    # https://github.com/riscv/riscv-docs-base-container-image
    # https://hub.docker.com/r/riscvintl/riscv-docs-base-container-image
    - name: Pull Container
      run: |
        docker pull riscvintl/riscv-docs-base-container-image:latest

    # Build PDF and HTML files using the container
    - name: Build Files
      run: |
        docker run --rm -v ${{ github.workspace }}:/build riscvintl/riscv-docs-base-container-image:latest \
        /bin/sh -c 'cd ./build && make'

    # Set the short SHA for use in artifact names
    - name: Set short SHA
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV

    # Upload the priv-isa-asciidoc PDF file
    - name: Upload priv-isa-asciidoc.pdf
      uses: actions/upload-artifact@v3
      with:
        name: priv-isa-asciidoc-${{ env.SHORT_SHA }}.pdf
        path: ${{ github.workspace }}/build/priv-isa-asciidoc.pdf
        retention-days: 7

    # Upload the priv-isa-asciidoc HTML file
    - name: Upload priv-isa-asciidoc.html
      uses: actions/upload-artifact@v3
      with:
        name: priv-isa-asciidoc-${{ env.SHORT_SHA }}.html
        path: ${{ github.workspace }}/build/priv-isa-asciidoc.html
        retention-days: 7

    # Upload the unpriv-isa-asciidoc PDF file
    - name: Upload unpriv-isa-asciidoc.pdf
      uses: actions/upload-artifact@v3
      with:
        name: unpriv-isa-asciidoc-${{ env.SHORT_SHA }}.pdf
        path: ${{ github.workspace }}/build/unpriv-isa-asciidoc.pdf
        retention-days: 7

    # Upload the unpriv-isa-asciidoc HTML file
    - name: Upload unpriv-isa-asciidoc.html
      uses: actions/upload-artifact@v3
      with:
        name: unpriv-isa-asciidoc-${{ env.SHORT_SHA }}.html
        path: ${{ github.workspace }}/build/unpriv-isa-asciidoc.html
        retention-days: 7
